language: python
python:
  - "2.6"
  - "2.7"

env:
  global:
    - PYTHONPATH=~/gaesdk/google_appengine

  matrix:
    - USE_EXTENSIONS=true # no dependencies
    - USE_EXTENSIONS=false # no dependencies
    - DJANGO_VERSION=1.2.7
    - DJANGO_VERSION=1.3.7
    - DJANGO_VERSION=1.5.12
    - DJANGO_VERSION=1.7.3
    - SQLALCHEMY_VERSION=0.7.10
    - SQLALCHEMY_VERSION=0.8.7
    - SQLALCHEMY_VERSION=0.9.8
    - TWISTED_VERSION=14.0.2
    - GAESDK_VERSION=1.9.17

matrix:
  exclude:
    # Django 1.7 dropped support for python 2.6
    - python: "2.6"
      env: DJANGO_VERSION=1.7.3
    # Google AppEngine SDK dropped support for python 2.6
    - python: "2.6"
      env: GAESDK_VERSION=1.9.17

before_install:
  - pip install flake8
  - flake8

install:
  - pip install coverage coveralls
  - pip install -e .
  - ./install_optional_dependencies.sh
  - ./maybe_install_cython.sh

script:
  - coverage run --source=pyamf setup.py test

after_success:
  - coveralls
